runtime: python39

handlers:
- url: /(.*\.(gif|png|jpg|ico|txt))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|ico|txt)$

- url: /(.*\.(html|css|js))$
  static_files: public/\1
  upload: public/.*\.(html|css|js)$

- url: /(.*)/$
  static_files: public/\1/index.html
  upload: public/.*/index.html

- url: /(.*)
  static_files: public/\1.html
  upload: public/.*.html

- url: /
  static_files: public/index.html
  upload: public/index.html
