runtime: python39

handlers:
  # Serve static assets (images, CSS, JS, etc.)
  - url: /images
    static_dir: images

  - url: /static
    static_dir: static

  # Serve directory URLs (like /about/)
  - url: /(.*)/$
    static_files: public/\1/index.html
    upload: public/.*/index.html

  # Serve clean URLs without .html (like /about)
  - url: /(.*)
    static_files: public/\1.html
    upload: public/.*.html

  # Serve root index.html for the home page
  - url: /
    static_files: public/index.html
    upload: public/index.html
