backend:
  name: github
  repo: Syberkey/syberkey-site
  branch: main
  base_url: https://oauth-service-dot-inspired-verve-426108-s7.ts.r.appspot.com
  auth_endpoint: auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}

  - name: "settings"
    label: "Settings"
    files:
      - file: "data/contact.yml"
        label: "Contact Information"
        name: "contact"
        fields:
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}