name: Deploy to Google Cloud App Engine

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo site
      run: hugo --minify

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Enable necessary APIs
      run: |
        gcloud services enable appengine.googleapis.com
        gcloud services enable cloudbuild.googleapis.com
        gcloud services enable cloudresourcemanager.googleapis.com

    - name: Deploy to App Engine
      run: |
        echo "runtime: python39" > public/app.yaml
        echo "handlers:" >> public/app.yaml
        echo "- url: /(.*)" >> public/app.yaml
        echo "  static_files: \1" >> public/app.yaml
        echo "  upload: (.*)" >> public/app.yaml
        cd public && gcloud app deploy --quiet