name: Deploy to Google Cloud App Engine

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo site
      run: hugo --minify

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to App Engine
      run: |
        echo "runtime: python39" > public/app.yaml
        echo "handlers:" >> public/app.yaml
        echo "- url: /(.*)" >> public/app.yaml
        echo "  static_files: \1" >> public/app.yaml
        echo "  upload: (.*)" >> public/app.yaml
        cd public && gcloud app deploy --quiet
